### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by toastedcrumpets** [inventree/inventree-python#113]
I was working on a 'stock/transfer' endpoint implementation in this library, and I keep running into a strange error where the inventree API reports a field is required, even when its provided.

I tried checking your unit tests to see if you're picking up similar errors, but I notice they're silently failing:
https://github.com/inventree/inventree-python/runs/6958148020?check_suite_focus=true

Should your CI report these checks failing?

**Comment by matmair** [comment]
Hi there @toastedcrumpets and thank you for your report!
I am not really part of this part of the ecosystem but to me it seems like the assertions are met.
Maybe @eeintech or @SchrodingersGat can make light of the situation.

A transfer function sounds exciting. Eager to see what you come up with. If you want feedback there is always the option to create a draft PR.

**Comment by toastedcrumpets** [comment]
Ah, my mistake, they are intentional fails but they're being logged to output as well as handled. Thanks for the reply!
