### ISSUE TITLE
Filtering to null values

### ISSUE THREAD

**Issue by martonmiklos** [inventree/inventree-python#146]
I have added the parent_id for the filtering fields in the InvenTree #3876, however I do not know how to filter the categories without parent.

If I do a 
`>>> cats = PartCategory.list(api, parent_id='')`
It ends up in a request:
`[28/Oct/2022 22:01:54] "GET /api/part/category/?parent_id= HTTP/1.1" 200 470422
`
but it sends back all categories.

Is there any trick what I am missing?

**Comment by SchrodingersGat** [comment]
Use the `parent` field (not `parent_id`), and specify "None"  or "null"

![image](https://user-images.githubusercontent.com/10080325/198746175-beefccdc-e865-430c-bf7d-106a475d1316.png)

**Comment by martonmiklos** [comment]
I apologize for being blind. I think I will improve the docs with this.
