### ISSUE TITLE
Cannot authenticate using python inventree library (and username/password, not token login)

### ISSUE THREAD

**Issue by rrakso** [inventree/inventree-python#18]
`Basic auth` is used in library
![image](https://user-images.githubusercontent.com/23143274/81749952-e675ff80-94ac-11ea-938d-17b485a64250.png)
but it doesn't work, also in file `api.py` at line [79](https://github.com/inventree/inventree-python/blob/master/inventree/api.py#L79) is 
` reply = requests.get(token_url, auth=self.auth)` but it should be ` reply = requests.post(token_url, auth=self.auth)`

Methods which work are:
- `application/json`
![image](https://user-images.githubusercontent.com/23143274/81751169-2dfd8b00-94af-11ea-9627-67310f475d08.png)
- `multipart/form-data`
![image](https://user-images.githubusercontent.com/23143274/81751223-4ff70d80-94af-11ea-99b3-e66e32fb345f.png)
- `application/x-www-form-urlencoded`
![image](https://user-images.githubusercontent.com/23143274/81751302-76b54400-94af-11ea-967d-4ef7eb816c4f.png)

When I make `api = InvenTreeAPI('http://jarvis.net.pl:6456/api/', token="<token>", verbose=True)` then everythnig is ok.

##### Used envoirment
The output of `http://jarvis.net.pl:6456/api/` is 
```json
{"server": "InvenTree", "version": "0.0.11_pre", "instance": "aa90ab9e02164313a826ec8f7ca67b7a"}
```

**Comment by SchrodingersGat** [comment]
@rrakso you may need to update InvenTree - the API for token authentication was changed slightly since the version you are on.
