### ISSUE TITLE
Typo in classname: inventree.label.LabelPrintingMixing

### ISSUE THREAD

**Issue by Petrox** [inventree/inventree-python#204]
I think the intended classname was inventree.label.LabelPrintingMixin

**Comment by wolflu05** [comment]
Where do you see this error? Please use the issue templates and proved some more information.

**Comment by Petrox** [comment]
Note: this MIGHT break code that uses the original classname (I did a search on github with no results though)

Optional smooth transition: the original LabelPrintingMixing class could be created as a child of the LabelPrintingMixin marked as obsolete with a target date of removal, so it won't break code quickly, (maybe emit some warnings on initialization?)

**Comment by miggland** [comment]
Closing because completed in #205
