### ISSUE TITLE
Remove class FILTERS variable

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-python#22]
Should not limit the filters to what is described in the FILTERS list! There's no point!

**Comment by eeintech** [comment]
@SchrodingersGat I am curious, what was the purpose of these filters?

**Comment by SchrodingersGat** [comment]
Honestly I'm not really sure what past-me was thinking. Artificially setting these filters means that you have to update inventree-python filters whenever the core InvenTree API changes. It would be much cleaner to just remove them.

I *think* that it was to ensure that other import keywords don't get mistaken as API filters.

**Comment by eeintech** [comment]
I see. It shouldn't be much work to remove them, I may get the chance to do it this week.

**Comment by eeintech** [comment]
@SchrodingersGat Should we close this issue?

**Comment by SchrodingersGat** [comment]
Yep, thanks!
