### ISSUE TITLE
Setting Part Minimum and Maximum cost from API

### ISSUE THREAD

**Issue by realstudent01** [inventree/inventree-python#238]
When looking through the API, there are some functions relating to part cost. However, when I use these commands I'm not seeing a change in the value listed for the parts, and I believe that's because it's not setting the right values. Is there a function that modifies the "Minimum Cost" and "Maximum Cost" for a given part?

I've been trying to do:
```
parts = Part.list(api)
for part in parts:
part._data['pricing_min'] = 1
part._data['pricing_max'] = 10
part.save()
```

I also tried the following, which also does not work:
```
parts = Part.list(api)
for part in parts:
part.save(data={'pricing_min': 1, 'pricing_max': 10})
```

**Comment by SchrodingersGat** [comment]
This is because "pricing" data is actually in a different table in the database - and those values are read-only.

The pricing data for a part is available at `/api/part/<id>/pricing/` - currently this is not implemented in this python binding.

**Comment by realstudent01** [comment]
Sorry, I see you meant to use it with the requests library.
