### ISSUE TITLE
Repeated API Connection crash when uploading large number of parameters

### ISSUE THREAD

**Issue by realstudent01** [inventree/inventree-python#240]
I am trying to upload a large number of parameters from a script with the line `param = Part.Parameter.create(api,{'part': part, 'template': template, 'data': value})`. It works for a while and then fails with the following error. Adding a .05 second wait afterwards seems to allow it to work for longer, but it still crashes.

<div class="adn ads" data-message-id="#msg-f:1807933642048172240" data-legacy-message-id="191712118fc270d0" style="border-left: none; padding: 0px; display: flex; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gs" style="margin: 0px; min-width: 0px; padding: 0px 0px 20px; width: initial;"><div class=""><div id=":18v" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTgwNzkzMzY0MjA0ODE3MjI0MCJd; 4:WyIjbXNnLWY6MTgwNzkzMzY0MjA0ODE3MjI0MCIsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDBd" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":18w" class="a3s aiL msg-8133587775983962544" style="direction: initial; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div lang="EN-US" link="#467886" vlink="#96607D" style="overflow-wrap: break-word;"><div class="m_-8133587775983962544WordSection1"><p class="MsoNormal" style="margin: 0px;">Error at api.request - POST @<span> </span><a href="http://server/api/part/parameter/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://server/api/part/parameter/&amp;source=gmail&amp;ust=1724266445218000&amp;usg=AOvVaw2Aa4QLKo-ubWxTSFZnKa2t" style="color: rgb(17, 85, 204);">http://server/api/part/<wbr>parameter/</a><u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">Traceback (most recent call last):<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connectionpool.py", line 789, in urlopen<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = self._make_request(<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connectionpool.py", line 536, in _make_request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = conn.getresponse()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connection.py", line 464, in getresponse<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    httplib_response = super().getresponse()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">                       ^^^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 1428, in getresponse<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response.begin()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 331, in begin<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    version, status, reason = self._read_status()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">                              ^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 300, in _read_status<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise RemoteDisconnected("Remote end closed connection without"<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">http.client.<wbr>RemoteDisconnected: Remote end closed connection without response<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;"> <u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">During handling of the above exception, another exception occurred:<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;"> <u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">Traceback (most recent call last):<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>adapters.py", line 667, in send<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    resp = conn.urlopen(<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">           ^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connectionpool.py", line 843, in urlopen<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    retries = retries.increment(<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">              ^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>util\retry.py", line 474, in increment<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise reraise(type(error), error, _stacktrace)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>util\util.py", line 38, in reraise<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise value.with_traceback(tb)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connectionpool.py", line 789, in urlopen<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = self._make_request(<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connectionpool.py", line 536, in _make_request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = conn.getresponse()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\urllib3\<wbr>connection.py", line 464, in getresponse<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    httplib_response = super().getresponse()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">                       ^^^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 1428, in getresponse<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response.begin()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 331, in begin<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    version, status, reason = self._read_status()<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">                              ^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\http\client.py", line 300, in _read_status<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise RemoteDisconnected("Remote end closed connection without"<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">urllib3.exceptions.<wbr>ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;"> <u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">During handling of the above exception, another exception occurred:<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;"> <u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">Traceback (most recent call last):<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "main.py", line 823, in &lt;module&gt;<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    param = P.Parameter.create(api, { 'part': value.part, 'template': value.template, 'data': value.data})<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\inventree\<wbr>base.py", line 191, in create<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response =<span> </span><a href="http://api.post/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://api.post&amp;source=gmail&amp;ust=1724266445218000&amp;usg=AOvVaw1FcXZrnsX-G9_yteoZgVfc" style="color: rgb(17, 85, 204);">api.post</a>(cls.URL, data, **kwargs)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\inventree\<wbr>api.py", line 426, in post<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = self.request(<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\inventree\<wbr>api.py", line 346, in request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise e<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\inventree\<wbr>api.py", line 338, in request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    response = methods[method](api_url, **payload)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>api.py", line 115, in post<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    return request("post", url, data=data, json=json, **kwargs)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>api.py", line 59, in request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    return session.request(method=method, url=url, **kwargs)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^^^^^^^^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>sessions.py", line 589, in request<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    resp = self.send(prep, **send_kwargs)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>sessions.py", line 703, in send<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    r = adapter.send(request, **kwargs)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">  File "FilePath\Python\Python312\<wbr>Lib\site-packages\requests\<wbr>adapters.py", line 682, in send<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">    raise ConnectionError(err, request=request)<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;">requests.exceptions.<wbr>ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))<u></u><u></u></p><p class="MsoNormal" style="margin: 0px;"><u></u> <u></u></p><div class="yj6qo"></div><div class="adL"></div></div><div class="adL"></div></div><div class="adL"></div></div></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: rgb(255, 255, 255); color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gB xu" jslog="184332; u014N:xr6bB;" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":18u">

</div></div></div></div>Error at api.request - POST @ http://server/api/part/parameter/

Traceback (most recent call last):

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen

    response = self._make_request(

               ^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request

    response = conn.getresponse()

               ^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse

    httplib_response = super().getresponse()

                       ^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\http\client.py", line 1428, in getresponse

    response.begin()

  File "FilePath\Python\Python312\Lib\http\client.py", line 331, in begin

    version, status, reason = self._read_status()

                              ^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\http\client.py", line 300, in _read_status

    raise RemoteDisconnected("Remote end closed connection without"

http.client.RemoteDisconnected: Remote end closed connection without response

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "FilePath\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send

    resp = conn.urlopen(

           ^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen

    retries = retries.increment(

              ^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 474, in increment

    raise reraise(type(error), error, _stacktrace)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\util\util.py", line 38, in reraise

    raise value.with_traceback(tb)

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen

    response = self._make_request(

               ^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request

    response = conn.getresponse()

               ^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse

    httplib_response = super().getresponse()

                       ^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\http\client.py", line 1428, in getresponse

    response.begin()

  File "FilePath\Python\Python312\Lib\http\client.py", line 331, in begin

    version, status, reason = self._read_status()

                              ^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\http\client.py", line 300, in _read_status

    raise RemoteDisconnected("Remote end closed connection without"

urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "main.py", line 823, in <module>

    param = P.Parameter.create(api, { 'part': value.part, 'template': value.template, 'data': value.data})

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\inventree\base.py", line 191, in create

    response = [api.post](http://api.post/)(cls.URL, data, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\inventree\api.py", line 426, in post

    response = self.request(

               ^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\inventree\api.py", line 346, in request

    raise e

  File "FilePath\Python\Python312\Lib\site-packages\inventree\api.py", line 338, in request

    response = methods[method](api_url, **payload)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post

    return request("post", url, data=data, json=json, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request

    return session.request(method=method, url=url, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request

    resp = self.send(prep, **send_kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send

    r = adapter.send(request, **kwargs)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "FilePath\Python\Python312\Lib\site-packages\requests\adapters.py", line 682, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by matmair** [comment]
Sounds like you are getting rate-limited by either the server or your reverse proxy.
Are there errors thrown on the server? You should see them in your notifications if you are logged in asa superuser. If there are none it is probably a rate limit

**Comment by realstudent01** [comment]
I've found a way around the reverse proxy issue, but I am now getting a server timeout. `requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=10)`. Is there a way to increase the timeout through the API?

**Comment by realstudent01** [comment]
Nevermind

**Comment by SchrodingersGat** [comment]
> I've found a way around the reverse proxy issue

What was the solution here @realstudent01  - in case it helps other users with a similar issue

**Comment by realstudent01** [comment]
Unfortunately, it wasn't much of a solution... I simply switched to the inventree server I have running that has less firewalls in the way. My plan was to work on that one and then just import that database to the one that is more protected with mySQL manager.
