### ISSUE TITLE
[How-To] Delete inactive part permanently

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-python#31]
Hey there,

I'm not able to delete a part permanently using the inventree module, here's my shell log:
```
>>> from inventree.api import InvenTreeAPI
>>> from inventree.part import Part
>>> api = InvenTreeAPI('http://127.0.0.1:8000/', username='admin', password='admin')
>>> part = Part(api, 38)
>>> print(part.name)
RES 10.0K OHM 1/4W 5% AXIAL
>>> part.active = False
>>> part.save()
>>> print(part.active)
False
>>> part.delete()
WARNING:root:Bad response (405) - DELETE 'http://127.0.0.1:8000/api/part/38/' - {"detail":"Method \"DELETE\" not allowed."}
405 {"detail":"Method \"DELETE\" not allowed."}
```

Do you know why the `DELETE` method is not allowed on inactive parts?
Username and password are my superuser/admin credentials.

**Comment by SchrodingersGat** [comment]
DELETE was explicitly disallowed to prevent parts being deleted. But now there is the concept of "inactive" parts being deleted. It would be a good idea to add the DELETE endpoint back in, but throw an error if the part is actually active (and *not* delete it in this case).

This would mean a chance is required to the main inventree code base

**Comment by eeintech** [comment]
@SchrodingersGat Ok I dug inside the API implementation to try to allow, this see pull request: https://github.com/inventree/InvenTree/pull/883

**Comment by eeintech** [comment]
Also FYI, to change the `active` state of a part, it seems like this does **not** work:
```
    part.active = False
    part.save()
```
But this code works:
```
    part._data['active'] = False
    part.save()
```
