### ISSUE TITLE
Adding new Part or StockItem via API requires placeholder 'pk' 

### ISSUE THREAD

**Issue by rco3** [inventree/inventree-python#37]
When creating a new Part or StockItem via api call, the process fails unless a placeholder value is given for 'pk'.  Apparently, something downstream insists upon removing this 'pk', and gets upset if it isn't there to be removed.

```
item = StockItem.create(api, {
        'part_id': 25,
        'quantity': 125,
        'notes': 'gift from Rick Cliff',
        'status': 10,
        'location': 10  # PK of a StockLocation already in the database...
    })
Traceback (most recent call last):

  File "<ipython-input-101-200306407752>", line 1, in <module>
    item = StockItem.create(api, {

  File "/Users/rco3/Dropbox/Projects/Parts Counter/python code/Inventree/inventree-python/inventree_object.py", line 44, in create
    del data['pk']

KeyError: 'pk'
```

Instance Name | foo
-- | --
   InvenTree Version | 0.1.3 pre
   Django Version | 3.0.7
   Commit Hash | 2c1d585f
   Commit Date | 2020-08-27

**Comment by eeintech** [comment]
@rco3 How are you creating Part items? Can you show what error you're getting?

**Comment by rco3** [comment]
From command line or called from script:

```
newPart = Part.create(api, {
            'name': 'Resistor, '+value+', metal film, RN55C',
            'description': 'RN55C type Metal Film resistor',
            'category': 6,
            'active': True,
            'virtual': False,
            'IPN': 'ECR-RN55C-'+value,
            'assembly': False,
            'component': True,
            'is_template': False,
            'purchaseable': True,
            'salable': False,
            'starred': False,
            'trackable': False,
            'virtual': False,
            'units': 'pcs',
            'keywords': 'RN55C '+value
            # Note - You do not have to fill out *all* fields
        })
Traceback (most recent call last):

  File "<ipython-input-13-45951a5cd5b9>", line 1, in <module>
    newPart = Part.create(api, {

  File "/Users/rco3/Dropbox/Projects/Parts Counter/python code/Inventree/inventree-python/inventree_object.py", line 44, in create
    del data['pk']

KeyError: 'pk'
```

In either the case of Part creation or StockItem creation, the absence of a field and value for 'pk' in the newly created object throws the above error.  If I place a line : 'pk': 999, then I do not get the error and object creation proceeds as expected, and the new object has a new 'pk' value (not 999) assigned.  StockItem creation fails for reasons detailed in another Issue, but Part creation works as expected (aside from this workaround). I have made many Parts this way. Smiley, happy.

**Comment by SchrodingersGat** [comment]
Looks like your `inventree-python` version is super out of date! Update to the latest version and it should be all good

`pip install --upgrade inventree`

**Comment by rco3** [comment]
Hm.  Interesting.  That does seem to have resolved it.  I had just installed inventree via pip within the last couple of days, I swear.  

Glad it was that easy.
