### ISSUE TITLE
search terms in Company.list() do nothing

### ISSUE THREAD

**Issue by rco3** [inventree/inventree-python#38]
MFGs=Company.list(api, is_manufacturer=True)
When trying to retrieve a list of Manufacturers, the use of the is_manufacturer parameter does nothing.  All companies are returned regardless of the value passed for this parameter: True, False, 1, 0, doesn't matter.  Nor does is_supplier, etc. work.

What am I missing?

**Comment by eeintech** [comment]
@rco3 Weird, it works for me I just checked. Are you on the latest commit or on the latest PyPI release?

**Comment by eeintech** [comment]
Ok so last PyPI version has same issue for `is_manufacturer` but `is_supplier` works fine in my testing.
Maybe it's time for a new release :smiley: 

@rco3 If you are using the last PyPI release then I think this should be fixed going with a clone of the repo instead

**Comment by SchrodingersGat** [comment]
I've bumped the version number and uploaded a new version to PIP. This should fix the filtering issues as they've been fixed in "latest" version for a while.

`pip install inventree --upgrade`

**Comment by rco3** [comment]
Oliver, that nailed it.  I had already tried updating inventree through pip - I've been caught in that trap once already - but I was up-to-date already.  With your new push to PIP, problem solved.  THANK YOU.

**Comment by rco3** [comment]
I did try updating PyPI as you suggested, thank you @eeintech, but that didn't get me there.  I hadn't yet gotten to the point of installing inventree-python from repo instead of from pip when @SchrodingersGat obviated the need. Thanks for helping figure this out.
