### ISSUE TITLE
Crashes if Server is not Available

### ISSUE THREAD

**Issue by lookme2** [inventree/inventree-python#48]
So I have been working on a small project at work using the python api.  When the server is not available the program crashes.  It looks like when the test_server is called it either returns a True/False but back in _init_ it is never checked.  

Question is am I looking at this right or should I check to see if the server is there before I call the python api?

**Comment by SchrodingersGat** [comment]
The `init` function should do something with the result of `testServer()` , you are right.

Throw an exception, maybe?

**Comment by lookme2** [comment]
Either that or just return a True/False maybe?

**Comment by SchrodingersGat** [comment]
the `__init__` function cannot return a value though

**Comment by lookme2** [comment]
I look right over that.  You are correct.
