### ISSUE TITLE
Add support for ManufacturerPart model

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-python#53]
https://github.com/inventree/InvenTree/pull/1417

**Comment by eeintech** [comment]
@SchrodingersGat You can assign it to me if you want. I should have time this week along with the doc.

**Comment by eeintech** [comment]
Note that creating SupplierPart, automatically creates a ManufacturerPart so support is for direct management of ManufacturerPart objects.

**Comment by eeintech** [comment]
@SchrodingersGat Done!
