### ISSUE TITLE
Wrapper class and command line functions

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-python#66]
@SchrodingersGat @matmair This is an idea that sparked into my head following the conversation here: https://github.com/inventree/InvenTree/issues/1421

What do you think of a wrapper/master class that can handle all underlying API functions to create a simpler experience using the API? Obviously it would handle errors, checks, permissions, etc.

I'm think something similar to what I did for Ki-nTree (except it is not wrapped into a class):
https://github.com/sparkmicro/Ki-nTree/blob/master/database/inventree_api.py

Another goal would be to accelerate the integration and offer quick hooks to other services like 3rd party apps.

### Create a part
``` python
api = InvenTreeAPI(...)

api.Part(function=part.CREATE, category='Resistors', name='A New Part', description='Testing the API', revision='1', type=part_type.COMPONENT)
```

### Update Purchase Order
``` python
api = InvenTreeAPI(...)

new_part = api.Part(function=part.GET, name='A New Part', category='Resistors')
api.PurchaseOrder(function=po.ADDLINEITEM, part=new_part, quantity=10, puchase_price=2.15)
```

## Command-line

I'm thinking also we could support command-line functions, like:

``` bash
$ inventree_api part --function create --category 'Resistors' --name 'A New Part' --description 'Testing the API' --revision 1 --type component
```

**Comment by eeintech** [comment]
Never mind, don't think this is a desired approach

**Comment by matmair** [comment]
@eeintech I would like the idea but seems a bit difficult, have you thought about how to implement it?

**Comment by eeintech** [comment]
@matmair take a look at #71 but you are right I'm abandoning this endeavor because it does not benefit integration with 3rd party apps. Command-line controls can be nice but don't think anybody will find them useful in the end, easier to interface with JSON or InvenTree objects directly.

**Comment by matmair** [comment]
@eeintech nice implementation. You are probably right about low usage.

**Comment by eeintech** [comment]
@matmair Thanks, it can be nice to interact with database using command-line too, and I discovered the `click` package which is quite fun to use, I think I'll forget about `argparse` from now on!

My biggest grief is that using API puts the bar quite high for novices, which I was few years back. There is quite a few checks to do before being able to, for instance, add a supplier part:
- does the supplier exist? if not it needs to be created -> need to request authorization from user
- are all the required fields present? request missing data from user then re-try
- does the supplier part exists already? handle API response with friendly error report
- etc

So I was thinking this could deserve a layer topping what's currently implemented. But then I realize that's maybe not the point of an API package, eg. make things easier for the user. Much more useful to have this implemented as part of a tool like [Ki-nTree](https://github.com/sparkmicro/Ki-nTree/) that has a real world use for it. Unless I'm seeing wrong here...

**Comment by matmair** [comment]
@eeintech I am currently (to be honest I am struggling for like 3 months) building a Fusion 360 plugin and there is so much to consider when interacting with the API / pypi package.
The user base for a CLI would probably be only a few humans but I find it generally hard to assess how many users of this ecosystem there are. But as there is not telemetry or similar we might never know.

**Comment by eeintech** [comment]
Is it an InvenTree plugin for Fusion360 or opposite? What's your strategy there?

**Comment by matmair** [comment]
It is kind of both; It can add a part from Fusion360 to InvenTree or safe a InvenTree part-association to a Fusion360 part. Additionally, it can read the structure of all parts in a file and save them into a parts BOM.
But it is not refined and I do not have a stable CI-pipeline for it. With the fast pace the API is developing right now I need that.

**Comment by SchrodingersGat** [comment]
Coming in late to this one but interested to hear more about your Fusion360 integration @matmair do you have a working example available?

**Comment by matmair** [comment]
@SchrodingersGat I have a quick and dirty thing running but it is not in a state I would recommend for production use. I have to look when I find time but I will try to clean it up and make it public.

**Comment by matmair** [comment]
@SchrodingersGat I got the plugin almost ready, would it be ok to use the InvenTree logo for it in the Autodesk store? I would like to submit it there (free of charge, the code is licensed under MIT) to enable easier installs for users and better discoverability.

**Comment by SchrodingersGat** [comment]
@matmair yes absolutely happy for you to use the logo. Please submit a PR to the documentation repo, adding a link under the "third party plugins" page :)
