### ISSUE TITLE
Saving pdf results on pc via python

### ISSUE THREAD

**Issue by StijnLoeys1999** [inventree/inventree-python#72]
Hey all, 

Sorry for the many questions over these last few weeks, they've been really helpfull!

Is there a way to save pdfs via the python interface? I have found that you can access the attachments via the getAttachments() method, but i find no way to really "save" them on my pc.

Kind regards

**Comment by StijnLoeys1999** [comment]
I think I found a way of accessing the url link via the API provided.
The problem however is that i can't download the file to my computer via python because I have to re-login then (but can't).
It does however work if i just copy and past the link. But the file itself won't open on my computer 
(example: 'https://ivt.arcsec.space/media/stock_files/306/Granta2020-installation.pdf' works as link for me (since i have access) but if i download it via python, i can't access it)

**Comment by eeintech** [comment]
@SchrodingersGat Which tool do you use for download?

Try this in your terminal:
``` bash
$ pip install wget
$ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wget
>>> wget.download('https://ivt.arcsec.space/media/stock_files/306/Granta2020-installation.pdf')
```

Does it download the file? It works for me using private domain too, as long as I'm on same network obviously :)

**Comment by SchrodingersGat** [comment]
Adding native file downloads (for attachments, images, etc) is a good idea. I'll look into this! Currently I don't have a standard way of achieving this integrated into the API

**Comment by SchrodingersGat** [comment]
@StijnLoeys1999 once https://github.com/inventree/inventree-python/pull/73 is merged, you can download files as follows:

```python
attachment.download("/home/user/custom_name.pdf")  # Will overwrite the filename
attachment.download("/home/user/")  # Will use the name of the attachment file
```
